trigger:
  branches:
    include:
      - main
      - feature/*
   
  paths:
    include:
      - SID-multi-environment/*
    exclude:
      - README.md

pr:
 branches:
   include:
     - main


schedules:
  - cron: "0 3 * * *"
    displayName: Daily Run
    branches:
      include:
        - main
    always: true

parameters:
  - name: environment
    displayName: Select Environment
    type: string
    default: dev
    values:
      - dev
      - test
      - prod

pool: may-pool
 
stages:
  - stage: FirstStage
    displayName: Init
    jobs:
      - job: terraforminit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'sid.tfstate'


  - stage: SecondStage
    displayName: Plan
    jobs:
      - job: terraformplan
        steps:
          

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'may-sc'

  - stage: ThirdStage
    displayName: Apply
    jobs:
      - job: terraformapply
        steps:
         
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'may-sc'

          